### ISSUE TITLE
`rotation_matrix` working?

### ISSUE THREAD

**Issue by gustavojra** [FermiQC/Molecules.jl#7]
I tried the following:
```
julia> v = [1.0, 1.0, 0.0]
julia> z = [0.0, 0.0, 1.0]
julia> M = rotation_matrix(z, 45.0)
julia> M * v
3-element Vector{Float64}:
 -0.3255815357163887
  1.3762255133518482
  0.0
```

Since `v` has an angle of 45 deg with either x or y, should this rotation about z yield a vector along x (or y depending on the direction that it is rotating?)

**Comment by sgoodlett** [comment]
Yeah, this is what happens when you don't convert from degrees to radians.......

I will fix this and include in my next push.

**Comment by gustavojra** [comment]
Ok, makes sense. So two things

- Documentation 
- Maybe some way to specify degree/rad?

In Julia, a function `f` normally has another version `fd` e.g. `cosd` for degrees. Maybe you could have a `rotarion_matrixd`? Or just add a keyword argument.

**Comment by gustavojra** [comment]
Not really a bug why the tag? :laughing:

**Comment by sgoodlett** [comment]
This issue has been fixed as there are now three functions for generating rotation matrices. `rotation_matrix` which accepts an angle in radians, `rotation_matrixd` which accepts an angle in degrees, and `Cn` which creates an n-fold rotation and is a nicer way to write things when looking for symmetry.
